### ISSUE TITLE
Admin Panel Login

### ISSUE THREAD

**Issue by keysinex** [faisalthaheem/denovo-voucher-script#1]
![microsoft edge 9_9_2018 8_16_47 am](https://user-images.githubusercontent.com/43112460/45264997-d457da00-b40a-11e8-9285-e847e46981fa.png)
This is the data after changing the debug value to 2 on the admin login screen. It still says invalid.

**Comment by faisalthaheem** [comment]
Can you please confirm the following

1. whether a user with email and pass exists with values "admin@voucherscript.com" and "6775edbef584f5fe26cf8213d53910780a67d41f"
2. the value of "Security.salt" and "Security.cipherSeed" in app/config/core.php
3. link to the instructions you followed for installation

Also, as you had communicated via email there appeared to be errors while executing the sql queries and i think your database is not correctly setup - please confirm you have rights to create views / procedures - these are usually not provisioned on shared hosting by default.

**Comment by keysinex** [comment]
1. Tried the login values and says invalid.
2. Attached screenshot
3. Attached screenshot
There was one error on the db.sql  installation file execution. See attached text file.
Files were uploaded to the root and database login values were set in database.php
![microsoft edge 9_10_2018 7_46_12 am](https://user-images.githubusercontent.com/43112460/45299025-df287280-b4cf-11e8-81bc-cae7ae0cc2fb.png)
![microsoft edge 9_10_2018 7_47_59 am](https://user-images.githubusercontent.com/43112460/45299039-ee0f2500-b4cf-11e8-8da5-5f9e031e81be.png)
[dbsql.txt](https://github.com/faisalthaheem/denovo-voucher-script/files/2366682/dbsql.txt)

**Comment by keysinex** [comment]
Reopen File

**Comment by keysinex** [comment]
Is there a new password to enter? Was the information helpful? What is required to access and edit the script?

**Comment by keysinex** [comment]
Can I help with providing any additional information?

**Comment by keysinex** [comment]
Hello again, I have been unable to access  the admin back office to edit my site openvouch.com. I read about this installation service in your instructions.  Can you assist with the password access or provide me the cost of your service?  
(Paid services are also available for installation. Please visit
http://www.voucherscript.com/professional-services.html for details
on "Professional Installation")
![microsoft edge 11_9_2018 1_29_54 pm](https://user-images.githubusercontent.com/43112460/48283942-a94a3080-e423-11e8-92d8-ea7b326ed2c1.png)

**Comment by faisalthaheem** [comment]
Hi, sorry I have been away due to some office work. 
Could you resolve the issue?
